// Code generated by "stringer -type=pill"; DO NOT EDIT.

package main

import "strconv"

const _pill_name = "placeboaspirinibuprofenparacetamol"

var _pill_index = [...]uint8{0, 7, 14, 23, 34}

func (i pill) String() string {
	if i < 0 || i >= pill(len(_pill_index)-1) {
		return "pill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pill_name[_pill_index[i]:_pill_index[i+1]]
}
