// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-02-15 12:55:56.073383828 &#43;0100 CET m=&#43;0.001123951
// using data from
// http://test.com
package project

var Contributors = []string{
	"Carl",
	"John",
	"Mike",
}
