// +build ignore

package main

import (
	"html/template"
	"log"
	"os"
	"time"
)

func main() {

	names := []string{}
	names = append(names, "Carl", "John", "Mike")
	url := "http://test.com"

	f, err := os.Create("contributors.go")
	if err != nil {
		log.Fatal(err)
	}
1	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		URL       string
		Names     []string
	}{
		Timestamp: time.Now(),
		URL:       url,
		Names:     names,
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
// using data from
// {{ .URL }}
package project

var Contributors = []string{
{{- range .Names }}
	"{{ . }}",
{{- end }}
}
`))
